#!/bin/bash

if [ "$#" -eq 0 ]
   then
   	make -f  Make_no_mpi clean
	make -f  Make_no_mpi MC -j3
	make -f  Make_no_mpi ENERG -j3
	make -f Make_no_mpi FINDMIN -j3
	make -f Make_no_mpi WFINDMAX -j3
	make -f Make_xyz clean
	make -f Make_xyz XYZENERG -j3
fi

if [ "$#" -eq 1 ]
then
    if [ $1 = "-MPI" ]
    then
	make -f Make_mpi clean
	make -f Make_mpi MPIMC -j3
	make -f Make_mpi T_ANN -j3
	make -f Make_mpi PT -j3
	make -f Make_mpi PFINDMIN -j3
    elif [ $1 = "-NBIA" ]
    then
	make -f Make_nbia clean
	make -f Make_nbia NBIANN -j3
    else
	echo "Invalid argument"
    fi
fi

if [ "$#" -gt 1 ]
then
    echo "Invalid number of arguments"
fi
